// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"giligili/app/chat/rpc/internal/logic"
	"giligili/app/chat/rpc/internal/svc"
	"giligili/app/chat/rpc/pb"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) SendChatMessage(ctx context.Context, in *pb.SendChatMessageReq) (*pb.Empty, error) {
	l := logic.NewSendChatMessageLogic(ctx, s.svcCtx)
	return l.SendChatMessage(in)
}

func (s *ChatServer) GetChatHistory(ctx context.Context, in *pb.GetChatHistoryReq) (*pb.GetChatHistoryResp, error) {
	l := logic.NewGetChatHistoryLogic(ctx, s.svcCtx)
	return l.GetChatHistory(in)
}
