// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "giligili/app/comment/api/internal/handler/comment"
	"giligili/app/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getVideoCommentList",
				Handler: comment.GetVideoCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getCommentReplyList",
				Handler: comment.GetCommentReplyListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/comment/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/commentVideo",
				Handler: comment.CommentVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/replyComment",
				Handler: comment.ReplyCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteComment",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/comment/v1"),
	)
}
