// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	video "giligili/app/video/api/internal/handler/video"
	"giligili/app/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getVideoList",
				Handler: video.GetVideoListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getVideoDetail",
				Handler: video.GetVideoDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/video/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uploadVideo",
				Handler: video.UploadVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteVideo",
				Handler: video.DeleteVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/likeVideo",
				Handler: video.LikeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/unlikeVideo",
				Handler: video.UnlikeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dislikeVideo",
				Handler: video.DislikeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/undislikeVideo",
				Handler: video.UndislikeVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendBarrage",
				Handler: video.SendBarrageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/video/v1"),
	)
}
