// Code generated by goctl. DO NOT EDIT.
package types

type SendChatMessageReq struct {
	ToUserId int    `json:"toUserId"`
	Content  string `json:"content"`
}

type SendChatMessageResp struct {
}

type GetChatHistoryReq struct {
	UserId int `json:"userId"`
}

type GetChatHistoryResp struct {
	ChatHistory []ChatMessage `json:"chatHistory"`
}

type ChatMessage struct {
	FromUserId       int    `json:"fromUserId"`
	FromUserNickname string `json:"fromUserNickname"`
	ToUserId         int    `json:"toUserId"`
	ToUserNickname   string `json:"toUserNickname"`
	Content          string `json:"content"`
	CreateTime       string `json:"createTime"`
}
