// Code generated by goctl. DO NOT EDIT.
package types

type Video struct {
	VideoId      int64  `json:"videoId"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	UserId       int64  `json:"userId"`
	UserNickname string `json:"userNickname"`
	Description  string `json:"description"`
	LikeCount    int64  `json:"likeCount"`
	DislikeCount int64  `json:"dislikeCount"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type GetVideoListReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	Keyword  string `json:"keyword"`
}

type GetVideoListResp struct {
	VideoList []Video `json:"videoList"`
}

type GetVideoDetailReq struct {
	VideoId int64 `json:"videoId"`
}

type GetVideoDetailResp struct {
	Video Video `json:"video"`
}

type Barrage struct {
	BarrageId    int64  `json:"barrageId"`
	UserId       int64  `json:"userId"`
	UserNickname string `json:"userNickname"`
	Text         string `json:"text"`
	Color        int64  `json:"color"`
	Type         int64  `json:"type"`
	Timestamp    int64  `json:"timestamp"`
}

type GetBarrageListReq struct {
	VideoId int64 `json:"videoId"`
}

type GetBarrageListResp struct {
	BarrageList []Barrage `json:"barrageList"`
}

type HotVideo struct {
	VideoId      int64  `json:"videoId"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	UserId       int64  `json:"userId"`
	UserNickname string `json:"userNickname"`
	Description  string `json:"description"`
	LikeCount    int64  `json:"likeCount"`
	DislikeCount int64  `json:"dislikeCount"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
	HotIndex     int64  `json:"hotIndex"`
}

type GetHotVideoListResp struct {
	HotVideoList []HotVideo `json:"hotVideoList"`
}

type UploadVideoReq struct {
	Title       string `form:"title"`
	Description string `form:"description"`
}

type UploadVideoResp struct {
	Success bool `json:"success"`
}

type DeleteVideoReq struct {
	VideoId int64 `json:"videoId"`
}

type DeleteVideoResp struct {
	Success bool `json:"success"`
}

type LikeVideoReq struct {
	VideoId int64 `json:"videoId"`
}

type LikeVideoResp struct {
	Success bool `json:"success"`
}

type UnlikeVideoReq struct {
	VideoId int64 `json:"videoId"`
}

type UnlikeVideoResp struct {
	Success bool `json:"success"`
}

type DislikeVideoReq struct {
	VideoId int64 `json:"videoId"`
}

type DislikeVideoResp struct {
	Success bool `json:"success"`
}

type UndislikeVideoReq struct {
	VideoId int64 `json:"videoId"`
}

type UndislikeVideoResp struct {
	Success bool `json:"success"`
}

type SendBarrageReq struct {
	VideoId   int64  `json:"videoId"`
	Text      string `json:"text"`
	Color     int64  `json:"color"`
	Type      int64  `json:"type"`
	Timestamp int64  `json:"timestamp"`
}

type SendBarrageResp struct {
	Success bool `json:"success"`
}
