// Code generated by goctl. DO NOT EDIT.
package types

type GetVideoListReq struct {
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
	Keyword  string `json:"keyword"`
}

type GetVideoListResp struct {
	VideoList []Video `json:"videoList"`
}

type Video struct {
	VideoId      int    `json:"videoId"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	UserId       int    `json:"userId"`
	UserNickname string `json:"userNickname"`
	Description  string `json:"description"`
	LikeCount    int    `json:"likeCount"`
	DislikeCount int    `json:"dislikeCount"`
	CommentCount int    `json:"commentCount"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type GetVideoDetailReq struct {
	VideoId int `json:"videoId"`
}

type GetVideoDetailResp struct {
	Video Video `json:"video"`
}

type UploadVideoReq struct {
	Title       string `form:"title"`
	Description string `form:"description"`
}

type UploadVideoResp struct {
	Success bool `json:"success"`
}

type LikeVideoReq struct {
	VideoId int `json:"videoId"`
}

type LikeVideoResp struct {
	Success bool `json:"success"`
}

type UnlikeVideoReq struct {
	VideoId int `json:"videoId"`
}

type UnlikeVideoResp struct {
	Success bool `json:"success"`
}

type DislikeVideoReq struct {
	VideoId int `json:"videoId"`
}

type DislikeVideoResp struct {
	Success bool `json:"success"`
}

type UndislikeVideoReq struct {
	VideoId int `json:"videoId"`
}

type UndislikeVideoResp struct {
	Success bool `json:"success"`
}
