// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatFieldNames          = builder.RawFieldNames(&Chat{})
	chatRows                = strings.Join(chatFieldNames, ",")
	chatRowsExpectAutoSet   = strings.Join(stringx.Remove(chatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatRowsWithPlaceHolder = strings.Join(stringx.Remove(chatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGiligiliChatIdPrefix = "cache:giligili:chat:id:"
)

type (
	chatModel interface {
		Insert(ctx context.Context, data *Chat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Chat, error)
		Update(ctx context.Context, data *Chat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChatModel struct {
		sqlc.CachedConn
		table string
	}

	Chat struct {
		Id         int64        `db:"id"`           // 聊天ID
		CreateTime time.Time    `db:"create_time"`  // 创建时间
		DeleteTime sql.NullTime `db:"delete_time"`  // 删除时间
		FromUserId int64        `db:"from_user_id"` // 发送者ID
		ToUserId   int64        `db:"to_user_id"`   // 接收者ID
		Content    string       `db:"content"`      // 聊天内容
	}
)

func newChatModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultChatModel {
	return &defaultChatModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`chat`",
	}
}

func (m *defaultChatModel) Delete(ctx context.Context, id int64) error {
	giligiliChatIdKey := fmt.Sprintf("%s%v", cacheGiligiliChatIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, giligiliChatIdKey)
	return err
}

func (m *defaultChatModel) FindOne(ctx context.Context, id int64) (*Chat, error) {
	giligiliChatIdKey := fmt.Sprintf("%s%v", cacheGiligiliChatIdPrefix, id)
	var resp Chat
	err := m.QueryRowCtx(ctx, &resp, giligiliChatIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatModel) Insert(ctx context.Context, data *Chat) (sql.Result, error) {
	giligiliChatIdKey := fmt.Sprintf("%s%v", cacheGiligiliChatIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, chatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.FromUserId, data.ToUserId, data.Content)
	}, giligiliChatIdKey)
	return ret, err
}

func (m *defaultChatModel) Update(ctx context.Context, data *Chat) error {
	giligiliChatIdKey := fmt.Sprintf("%s%v", cacheGiligiliChatIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.FromUserId, data.ToUserId, data.Content, data.Id)
	}, giligiliChatIdKey)
	return err
}

func (m *defaultChatModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGiligiliChatIdPrefix, primary)
}

func (m *defaultChatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChatModel) tableName() string {
	return m.table
}
