// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"giligili/app/user/rpc/internal/logic"
	"giligili/app/user/rpc/internal/svc"
	"giligili/app/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) FollowUser(ctx context.Context, in *pb.FollowUserReq) (*pb.Empty, error) {
	l := logic.NewFollowUserLogic(ctx, s.svcCtx)
	return l.FollowUser(in)
}

func (s *UserServer) UnfollowUser(ctx context.Context, in *pb.UnfollowUserReq) (*pb.Empty, error) {
	l := logic.NewUnfollowUserLogic(ctx, s.svcCtx)
	return l.UnfollowUser(in)
}
