// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "giligili/app/chat/api/internal/handler/chat"
	"giligili/app/chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sendChatMessage",
				Handler: chat.SendChatMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getChatHistory",
				Handler: chat.GetChatHistoryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/chat/v1"),
	)
}
