// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type RegisterResp struct {
	UserId int64 `json:"userId"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId       int64  `json:"userId"`
	Nickname     string `json:"nickname"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type GetUserInfoReq struct {
}

type GetUserInfoResp struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Avatar   string `json:"avatar"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type GetFollowerListReq struct {
}

type GetFollowerListResp struct {
	FollowerList []int `json:"followerList"`
}

type GetFolloweeListReq struct {
}

type GetFolloweeListResp struct {
	FolloweeList []int `json:"followeeList"`
}

type FollowUserReq struct {
	FolloweeId int `json:"followeeId"`
}

type FollowUserResp struct {
}

type UnfollowUserReq struct {
	FolloweeId int `json:"followeeId"`
}

type UnfollowUserResp struct {
}
