// Code generated by goctl. DO NOT EDIT.
package types

type GetCommentListReq struct {
	VideoId int `json:"videoId"`
}

type Comment struct {
	CommentId    int    `json:"commentId"`
	UserId       int    `json:"userId"`
	Content      string `json:"content"`
	LikeCount    int    `json:"likeCount"`
	DislikeCount int    `json:"dislikeCount"`
	ReplyCount   int    `json:"replyCount"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type GetCommentListResp struct {
	CommentList []Comment `json:"commentList"`
}

type CommentVideoReq struct {
	UserId  int    `json:"userId"`
	VideoId int    `json:"videoId"`
	Content string `json:"content"`
	ReplyId int    `json:"replyId"`
}

type CommentVideoResp struct {
	Success bool `json:"success"`
}

type ReplyCommentReq struct {
	UserId    int    `json:"userId"`
	CommentId int    `json:"commentId"`
	Content   string `json:"content"`
}

type ReplyCommentResp struct {
	Success bool `json:"success"`
}

type DeleteCommentReq struct {
	CommentId int `json:"commentId"`
}

type DeleteCommentResp struct {
	Success bool `json:"success"`
}
