// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"giligili/app/comment/rpc/internal/logic"
	"giligili/app/comment/rpc/internal/svc"
	"giligili/app/comment/rpc/pb"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) GetVideoCommentList(ctx context.Context, in *pb.GetVideoCommentListReq) (*pb.GetVideoCommentListResp, error) {
	l := logic.NewGetVideoCommentListLogic(ctx, s.svcCtx)
	return l.GetVideoCommentList(in)
}

func (s *CommentServer) GetCommentReplyList(ctx context.Context, in *pb.GetCommentReplyListReq) (*pb.GetCommentReplyListResp, error) {
	l := logic.NewGetCommentReplyListLogic(ctx, s.svcCtx)
	return l.GetCommentReplyList(in)
}

func (s *CommentServer) CommentVideo(ctx context.Context, in *pb.CommentVideoReq) (*pb.CommentVideoResp, error) {
	l := logic.NewCommentVideoLogic(ctx, s.svcCtx)
	return l.CommentVideo(in)
}

func (s *CommentServer) ReplyComment(ctx context.Context, in *pb.ReplyCommentReq) (*pb.ReplyCommentResp, error) {
	l := logic.NewReplyCommentLogic(ctx, s.svcCtx)
	return l.ReplyComment(in)
}

func (s *CommentServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentReq) (*pb.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
